# Latest version of ubuntu
FROM ubuntu:22.04

# update APT
RUN apt-get update

# upgrade current installed software through APT
RUN  apt-get upgrade -y

# install python3 and pip3
RUN apt-get install -y python3 python3-pip

# using pip3 to install flask
RUN pip3 install flask

# using pip3 to install flask-cors
RUN pip3 install flask-cors

# setting /app as working directory
WORKDIR /app

# Copy current directory contents into container at /app
COPY . /app 

#  open port 5252 to the world
EXPOSE 5252

# run api.py when the container launches
CMD ["python3", "api.py"]